### ISSUE TITLE
Make reactor tolerance a state variable

### ISSUE THREAD

**Issue by FlanFlanagan** [FlanFlanagan/Bright-lite#14]

**Comment by scopatz** [comment]
It is, I thought.  But it is mispelled.

**Comment by jimcc333** [comment]
It's not effectively used, I'll be improving it. We may need more than tolerance for various functions

**Comment by FlanFlanagan** [comment]
Cem says this is done

**Comment by scopatz** [comment]
But misspelled... please fix :)
