### ISSUE TITLE
mode 1 should skip timesteps

### ISSUE THREAD

**Issue by jimcc333** [FlanFlanagan/Bright-lite#23]

**Comment by scopatz** [comment]
What is mode 1?

**Comment by scopatz** [comment]
Just curious....

**Comment by jimcc333** [comment]
This refers to the fluence propagation mode in burnup calculations. mode 1 is the simplest, where the same fluence is added to every batch. in this case there is no benefit in taking time steps to propagate fluences since the end-of-cycle fluences can be easily found in one big timestep

**Comment by scopatz** [comment]
I see.
