### ISSUE TITLE
Investigate timing issues. 

### ISSUE THREAD

**Issue by FlanFlanagan** [FlanFlanagan/Bright-lite#9]
Speed up the Bright-lite

**Comment by FlanFlanagan** [comment]
Updated blending calc to take previous start up steady state blending fraction as first guess for fraction instead of 0.

**Comment by FlanFlanagan** [comment]
Removed building transmutation matrix for fuel during blending calculation. 

27% haste increase on test case.

**Comment by scopatz** [comment]
@FlanFlanagan - these don't seem to be on your timestep branch yet...

**Comment by scopatz** [comment]
also thanks!

**Comment by FlanFlanagan** [comment]
Done

**Comment by FlanFlanagan** [comment]
Reduced tolerance, errors not changing a whole lot. 33% haste.
